# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/cse_462/fgpa_convolution_acceleration/filter_hardware/filter_hardware.srcs/sources_1/bd/design_1/ip/design_1_filter_kernel_0_3/design_1_filter_kernel_0_3.xci
# IP: The module: 'design_1_filter_kernel_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/cse_462/fgpa_convolution_acceleration/filter_hardware/filter_hardware.gen/sources_1/bd/design_1/ip/design_1_filter_kernel_0_3/constraints/filter_kernel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_filter_kernel_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/cse_462/fgpa_convolution_acceleration/filter_hardware/filter_hardware.srcs/sources_1/bd/design_1/ip/design_1_filter_kernel_0_3/design_1_filter_kernel_0_3.xci
# IP: The module: 'design_1_filter_kernel_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/cse_462/fgpa_convolution_acceleration/filter_hardware/filter_hardware.gen/sources_1/bd/design_1/ip/design_1_filter_kernel_0_3/constraints/filter_kernel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_filter_kernel_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
