# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_filter_kernel_0_1/design_1_filter_kernel_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_filter_kernel_0_1 || ORIG_REF_NAME==design_1_filter_kernel_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_1/design_1_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_1 || ORIG_REF_NAME==design_1_axi_dma_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_xbar_1/design_1_axi_mem_intercon_imp_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_xbar_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_2/design_1_axi_mem_intercon_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_auto_us_2 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_auto_us_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_3/design_1_axi_mem_intercon_imp_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_auto_us_3 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_auto_us_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_1/design_1_axi_mem_intercon_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_auto_pc_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_1/design_1_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_1} -quiet] -quiet

# XDC: d:/cse_462/fgpa_convolution_acceleration/filter_hardware/filter_hardware.gen/sources_1/bd/design_1/design_1_ooc.xdc
